openapi: 3.0.0
info:
  title: ""
  description: ""
  version: ""
paths:
  /api/v1/branches:
    get:
      tags:
      - s3/Service
      parameters:
      - in: header
        name: authToken
        schema:
          type: string
          nullable: true
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  branches:
                    type: array
                    items:
                      type: number
  /api/v1/doc/{bucket}/{key}:
    get:
      tags:
      - s3/Service
      parameters:
      - in: path
        name: bucket
        required: true
        schema:
          type: string
      - in: path
        name: key
        required: true
        schema:
          type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  document:
                    type: array
                    items:
                      type: string
                      format: byte
    post:
      tags:
      - s3/Service
      parameters:
      - in: path
        name: bucket
        required: true
        schema:
          type: string
      - in: path
        name: key
        required: true
        schema:
          type: string
      requestBody:
        content:
          "":
            schema:
              type: object
              properties:
                document:
                  type: array
                  items:
                    type: string
                    format: byte
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                type: object
  /api/v1/multipart/{bucket}/{key}:
    post:
      tags:
      - s3/Service
      parameters:
      - in: path
        name: bucket
        required: true
        schema:
          type: string
      - in: path
        name: key
        required: true
        schema:
          type: string
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  additionalErrors:
                    type: object
                    properties:
                      lastName:
                        type: string
                      name:
                        type: string
                    nullable: true
                  data:
                    type: object
                    properties:
                      upload_id:
                        type: string
                  error:
                    type: boolean
                  errorText:
                    type: string
    patch:
      tags:
      - s3/Service
      parameters:
      - in: path
        name: bucket
        required: true
        schema:
          type: string
      - in: path
        name: key
        required: true
        schema:
          type: string
      requestBody:
        content:
          "":
            schema:
              type: object
              properties:
                document:
                  type: array
                  items:
                    type: string
                    format: byte
                partNumber:
                  type: number
                uploadID:
                  type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
    put:
      tags:
      - s3/Service
      parameters:
      - in: path
        name: bucket
        required: true
        schema:
          type: string
      - in: path
        name: key
        required: true
        schema:
          type: string
      requestBody:
        content:
          "":
            schema:
              type: object
              properties:
                uploadID:
                  type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
  /token:
    post:
      tags:
      - s3/Service
      parameters:
      - in: header
        name: authToken
        schema:
          type: string
          nullable: true
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grantType:
                  type: string
                scope:
                  type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  expiresIn:
                    type: number
                  token:
                    type: string
